# Generated by Django 6.0 on 2026-01-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10),
        ),
    ]
