# Generated by Django 6.0 on 2026-01-03 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
            ],
            options={
                'indexes': [models.Index(fields=['scheduled_time'], name='scheduler_s_schedul_891085_idx'), models.Index(fields=['is_sent'], name='scheduler_s_is_sent_d10ab3_idx')],
            },
        ),
    ]
